Bene
StudyProject-NLI/NLInterface pull request #9
Opened 2024-01-30 18:05 UTC by Bene0202

Moin, also ich habe vor allem mein eigens viewmodel hinzugefügt.  Dort sind mehrer Klassen drin. War für meine Übersicht um step für step vorzugehen. Kann sonst auch eine große Klasse mit den Funktionen machen. Dann habe ich in der MainActivity permisson request für die Kamera hinzugefügt (Sobald das nicht mehr die Handykamera ist fliegt das wahrscheinlich eh raus) und in onCreate das Scanning hinzugefügt. 
Ich habe im git ignore gesehen, dass gradle und so ignoriert wird, also weiß ich nicht ob du das sehen kannst. Musste auf jeden Fall dependencies hinzufügen und paar versionen updaten sowie targetSdk auf 34 setzen. Im Manifest habe ich auch meinen Service registriert. Sonst falls fragen sind zu irgendwas sag einfach Bescheid.
Bezüglich des Optivist Workshops: Ich habe in der Woche Blockseminar und bin daher nicht dabei. Falls ihr aber irgendwas von mir braucht sagt gerne Bescheid.

2024-02-05 08:20 UTC, mhaeming requested changes
An sich vom Code Stil und den Kommentaren super, aber ich bin kein Fan davon, den Scanner die ganze Zeit laufen zu haben und hätte gerne mehr Feedback oder zumindest Logs.

2024-02-05 08:20 UTC, mhaeming commented on .gitignore
Die Sachen zum ignore beziehen sich auf den `.gradle` und `.build` Ordner. Da sind nur temporäre Dateien drin, die eh nicht commited werden sollten.

2024-02-05 08:20 UTC, mhaeming commented on app/build.gradle
> +    implementation(platform('androidx.compose:compose-bom:2023.08.00'))
Du hast keine Compose Elemente in deinem Code, also sollten die dependencies auch nicht mehr dabei sein.

2024-02-05 08:20 UTC, mhaeming commented on app/build.gradle
> +        targetSdk 34
Änderung der Compile SDK finde ich in Ordnung, aber die TargetSDK sollte erst nach längerer Review angepasst werden. Da gibts ja in Android Studio auch einen Guide und Checker dafür.

2024-02-05 08:20 UTC, mhaeming commented on app/src/main/java/com/nlinterface/activities/MainActivity.kt
> +    private fun verifyCameraPermissions() {
Problem hierbei ist, dass du den Fall ohne Permissions nicht handlest. Als ich die App installiert habe, wollte er die ganze Zeit den service starten, ohne dass die Berechtigungen gegeben wurden und ist dann mehrfach dabei gecrasht, weil die Main Activity eher laden wollte, als das Pop Out für die Berechtigungen.

2024-02-05 08:20 UTC, mhaeming commented on app/src/main/java/com/nlinterface/viewmodels/BarcodeProductinfoViewModel.kt
> +                .addOnSuccessListener { barcodes ->
An dieser Stelle wäre vielleicht haptisches Feedback schön. Also ein kurzes Vibrieren, wenn ein Barcode gefunden wurde. Ich finde es nämlich aktuell etwas seltsam, dass man kein Preview Fenster hat und einfach er irgendwann anfängt vorzulesen.

2024-02-05 08:20 UTC, mhaeming commented on app/src/main/java/com/nlinterface/activities/MainActivity.kt
> +        startService(serviceIntent)
Bin mir auch nicht sicher, ob das Barcode-Scannen aktuell permanent als Service laufen sollte...das zieht ziemlich Akku, wenn die Kamera die ganze Zeit an ist. Vielleicht sollte es erst mal in eine separate Activity ausgelagert werden.

2024-02-05 14:04 UTC, Bene0202 commented
Danke für die ausführliche Rückmeldung. Sollte ich alles soweit hinbekommen. Mit dem Scanner stimme ich dir auf jeden Fall soweit zu. Ich glaube, ich hatte das mal in einer Sitzung angesprochen und daher kommt, dass ich das jetzt so umgesetzt habe. Ich meine mich zu erinnern, dass der Hintergedanke war, möglichst wenig Elemente in der App zu haben, die aktive Navigation erfordern, können das aber sonst auch gerne nochmal besprechen. Sollte grundsätzlich auf jeden Fall kein Problem sein.

2024-02-09 18:48 UTC, Bene0202 commented
Hab jetzt das meiste geändert. Das mit der Permission ist aktuell einfach über if gehandelt. Hab es jetzt auch erstmal dauerhaft laufend gelassen. Sobald nicht mehr die Handykamera sondern, die andere genutzt wird, sollte das auch keinen Akku mehr ziehen (also nicht mehr so viel). Und für die objectdectection wird der VideoStream ja sowieso permanent verarbeitet.

2024-02-11 11:21 UTC, mhaeming commented
Danke für die Änderungen! Sieht von meiner Seite soweit gut aus. Probleme, die Anwendung hatte, waren eher den API-Ergebnissen zuzuschreiben und für einen Prototyp absolut okay. Gute Arbeit! Ich merge es dann.

2024-02-11 11:21 UTC, merged